// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0QvJoWT90x337_pPk0K08NkvCR-hAMlM',
    appId: '1:848393432970:web:d030159605d6e7541a2273',
    messagingSenderId: '848393432970',
    projectId: 'acuroute-34d34',
    authDomain: 'acuroute-34d34.firebaseapp.com',
    storageBucket: 'acuroute-34d34.firebasestorage.app',
    measurementId: 'G-9FSN7520X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2xmjt1y9wo3s9jMSEOjC0r51iSQ5ydQ',
    appId: '1:848393432970:android:3088c0924955f2c11a2273',
    messagingSenderId: '848393432970',
    projectId: 'acuroute-34d34',
    storageBucket: 'acuroute-34d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBVf-MWKtVMMP_Ym82PE2keF-_XhIrR0',
    appId: '1:848393432970:ios:28644c33754ac6d31a2273',
    messagingSenderId: '848393432970',
    projectId: 'acuroute-34d34',
    storageBucket: 'acuroute-34d34.firebasestorage.app',
    iosBundleId: 'com.acuroute.acuroute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgBVf-MWKtVMMP_Ym82PE2keF-_XhIrR0',
    appId: '1:848393432970:ios:28644c33754ac6d31a2273',
    messagingSenderId: '848393432970',
    projectId: 'acuroute-34d34',
    storageBucket: 'acuroute-34d34.firebasestorage.app',
    iosBundleId: 'com.acuroute.acuroute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0QvJoWT90x337_pPk0K08NkvCR-hAMlM',
    appId: '1:848393432970:web:aa25dc820215f2f01a2273',
    messagingSenderId: '848393432970',
    projectId: 'acuroute-34d34',
    authDomain: 'acuroute-34d34.firebaseapp.com',
    storageBucket: 'acuroute-34d34.firebasestorage.app',
    measurementId: 'G-M126FGBP8V',
  );
}
